package prcomment

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
)

type Comment struct {
	Body string `json:"body"`
}

type PRCommentClient struct {
	token  string
	repo   string
	prNum  string
	client *http.Client
}

func New() *PRCommentClient {
	return &PRCommentClient{
		token:  os.Getenv("GITHUB_TOKEN"),
		repo:   os.Getenv("GITHUB_REPOSITORY"),
		prNum:  os.Getenv("GITHUB_PR_NUMBER"),
		client: &http.Client{},
	}
}

func (c *PRCommentClient) Post(body string) error {
	if c.token == "" || c.repo == "" || c.prNum == "" {
		return fmt.Errorf("GITHUB_TOKEN, GITHUB_REPOSITORY, and GITHUB_PR_NUMBER must be set")
	}

	url := fmt.Sprintf("https://api.github.com/repos/%s/issues/%s/comments", c.repo, c.prNum)

	comment := Comment{Body: body}
	data, err := json.Marshal(comment)
	if err != nil {
		return fmt.Errorf("marshaling comment: %w", err)
	}

	req, err := http.NewRequest("POST", url, bytes.NewReader(data))
	if err != nil {
		return fmt.Errorf("creating request: %w", err)
	}

	req.Header.Set("Authorization", "Bearer "+c.token)
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Accept", "application/vnd.github.v3+json")

	resp, err := c.client.Do(req)
	if err != nil {
		return fmt.Errorf("posting comment: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		body, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitHub API error %d: %s", resp.StatusCode, string(body))
	}

	return nil
}

func BuildCommentBody(scanResult []byte) string {
	var sb strings.Builder
	sb.WriteString("## Trusty Scan Results\n\n")

	var result map[string]interface{}
	if err := json.Unmarshal(scanResult, &result); err != nil {
		sb.WriteString("Error parsing scan results.\n")
		return sb.String()
	}

	if summary, ok := result["summary"].(map[string]interface{}); ok {
		total, _ := summary["total_issues"].(float64)
		score, _ := result["trust_score"].(float64)
		status, _ := summary["status"].(string)

		sb.WriteString(fmt.Sprintf("| Metric | Value |\n|---|---|\n"))
		sb.WriteString(fmt.Sprintf("| Trust Score | %d/100 |\n", int(score)))
		sb.WriteString(fmt.Sprintf("| Issues Found | %d |\n", int(total)))
		sb.WriteString(fmt.Sprintf("| Status | %s |\n", status))
		sb.WriteString("\n")
	}

	if files, ok := result["files"].([]interface{}); ok {
		for _, f := range files {
			file, _ := f.(map[string]interface{})
			path, _ := file["path"].(string)
			findings, _ := file["findings"].([]interface{})
			if len(findings) > 0 {
				sb.WriteString(fmt.Sprintf("### %s\n\n", path))
				sb.WriteString("| Rule | Severity | Message |\n|---|---|---|\n")
				for _, fi := range findings {
					finding, _ := fi.(map[string]interface{})
					rule, _ := finding["rule"].(string)
					sev, _ := finding["severity"].(float64)
					msg, _ := finding["message"].(string)
					sevStr := "info"
					if sev >= 3 {
						sevStr = "error"
					} else if sev >= 2 {
						sevStr = "warning"
					}
					sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", rule, sevStr, msg))
				}
				sb.WriteString("\n")
			}
		}
	}

	sb.WriteString("---\n")
	sb.WriteString("_Generated by Trusty AI Code Verification_")
	return sb.String()
}
