package mrcomment

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"

	"github.com/WorldOccupier/trusty/internal/types"
)

type Client struct {
	token     string
	projectID string
	mrIID     string
	host      string
	http      *http.Client
}

type note struct {
	Body string `json:"body"`
}

func New() *Client {
	host := os.Getenv("CI_SERVER_URL")
	if host == "" {
		host = "https://gitlab.com"
	}
	return &Client{
		token:     os.Getenv("GITLAB_TOKEN"),
		projectID: os.Getenv("CI_PROJECT_ID"),
		mrIID:     os.Getenv("CI_MERGE_REQUEST_IID"),
		host:      host,
		http:      &http.Client{},
	}
}

func (c *Client) Post(result *types.ScanResult) error {
	if c.token == "" || c.projectID == "" || c.mrIID == "" {
		return fmt.Errorf("GITLAB_TOKEN, CI_PROJECT_ID, and CI_MERGE_REQUEST_IID must be set")
	}

	body := buildCommentBody(result)
	note := note{Body: body}
	data, err := json.Marshal(note)
	if err != nil {
		return fmt.Errorf("marshaling note: %w", err)
	}

	url := fmt.Sprintf("%s/api/v4/projects/%s/merge_requests/%s/notes",
		strings.TrimRight(c.host, "/"), c.projectID, c.mrIID)

	req, err := http.NewRequest("POST", url, bytes.NewReader(data))
	if err != nil {
		return fmt.Errorf("creating request: %w", err)
	}

	req.Header.Set("PRIVATE-TOKEN", c.token)
	req.Header.Set("Content-Type", "application/json")

	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("posting comment: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 300 {
		respBody, _ := io.ReadAll(resp.Body)
		return fmt.Errorf("GitLab API error %d: %s", resp.StatusCode, string(respBody))
	}

	return nil
}

func buildCommentBody(result *types.ScanResult) string {
	var sb strings.Builder

	sb.WriteString("## Trusty Scan Results\n\n")
	sb.WriteString(fmt.Sprintf("**Trust Score:** %d/100 | **Issues:** %d | **Status:** %s\n\n",
		result.TrustScore, result.Summary.TotalIssues, result.Summary.Status))

	if result.Summary.TotalIssues == 0 {
		sb.WriteString(":white_check_mark: No issues found.\n")
		sb.WriteString("\n---\n_Generated by Trusty AI Code Verification_")
		return sb.String()
	}

	sb.WriteString("### Summary\n\n")
	sb.WriteString("| Metric | Value |\n|---|---|\n")
	sb.WriteString(fmt.Sprintf("| Trust Score | %d/100 |\n", result.TrustScore))
	sb.WriteString(fmt.Sprintf("| Total Issues | %d |\n", result.Summary.TotalIssues))
	sb.WriteString(fmt.Sprintf("| Errors | %d |\n", result.Summary.Errors))
	sb.WriteString(fmt.Sprintf("| Warnings | %d |\n", result.Summary.Warnings))
	sb.WriteString(fmt.Sprintf("| Files Scanned | %d |\n", result.Summary.FilesScanned))
	sb.WriteString(fmt.Sprintf("| Duration | %dms |\n\n", result.DurationMs))

	for _, f := range result.Files {
		if len(f.Findings) == 0 {
			continue
		}

		sb.WriteString(fmt.Sprintf("### %s\n\n", f.Path))
		sb.WriteString("| Severity | Rule | Line | Message |\n")
		sb.WriteString("|---|---|---|---|\n")

		for _, finding := range f.Findings {
			sev := "INFO"
			if finding.Severity == types.SeverityError {
				sev = "ERROR"
			} else if finding.Severity == types.SeverityWarning {
				sev = "WARN"
			}
			msg := strings.ReplaceAll(finding.Message, "|", "\\|")
			sb.WriteString(fmt.Sprintf("| %s | %s | %d | %s |\n", sev, finding.Rule, finding.Line, msg))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n")
	sb.WriteString("_Generated by Trusty AI Code Verification_")
	return sb.String()
}
