package jira

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"

	"github.com/WorldOccupier/trusty/internal/types"
)

type Client struct {
	host    string
	email   string
	token   string
	project string
	client  *http.Client
}

type createIssueRequest struct {
	Fields issueFields `json:"fields"`
}

type issueFields struct {
	Project     projectKey  `json:"project"`
	Summary     string      `json:"summary"`
	Description string      `json:"description"`
	IssueType   issueType   `json:"issuetype"`
	Priority    *priority   `json:"priority,omitempty"`
}

type projectKey struct {
	Key string `json:"key"`
}

type issueType struct {
	Name string `json:"name"`
}

type priority struct {
	Name string `json:"name"`
}

func New() *Client {
	return &Client{
		host:    os.Getenv("JIRA_HOST"),
		email:   os.Getenv("JIRA_EMAIL"),
		token:   os.Getenv("JIRA_API_TOKEN"),
		project: os.Getenv("JIRA_PROJECT"),
		client:  &http.Client{},
	}
}

func (c *Client) CreateIssues(result *types.ScanResult) ([]string, error) {
	if c.host == "" || c.email == "" || c.token == "" || c.project == "" {
		return nil, fmt.Errorf("JIRA_HOST, JIRA_EMAIL, JIRA_API_TOKEN, and JIRA_PROJECT must be set")
	}

	var keys []string
	for _, f := range result.Files {
		if len(f.Findings) == 0 {
			continue
		}

		var descParts []string
		descParts = append(descParts, fmt.Sprintf("h3. Findings in %s\n", f.Path))
		descParts = append(descParts, "|| Severity || Rule || Line || Message ||")
		highestSev := types.SeverityInfo

		for _, finding := range f.Findings {
			sev := "Info"
			if finding.Severity == types.SeverityError {
				sev = "Error"
				highestSev = types.SeverityError
			} else if finding.Severity == types.SeverityWarning {
				sev = "Warning"
				if highestSev < types.SeverityWarning {
					highestSev = types.SeverityWarning
				}
			}
			msg := finding.Message
			msg = strings.ReplaceAll(msg, "|", "\\|")
			descParts = append(descParts, fmt.Sprintf("| %s | %s | %d | %s |", sev, finding.Rule, finding.Line, msg))
			if finding.Suggestion != "" {
				suggestion := strings.ReplaceAll(finding.Suggestion, "|", "\\|")
				descParts = append(descParts, fmt.Sprintf("| Suggestion | | | %s |", suggestion))
			}
		}

		descParts = append(descParts, "\n---")
		descParts = append(descParts, fmt.Sprintf("h5. Trust Score: %d/100 | Duration: %dms", result.TrustScore, result.DurationMs))
		descParts = append(descParts, "_Generated by Trusty AI Code Verification_")

		summary := fmt.Sprintf("[Trusty] %d issue(s) in %s", len(f.Findings), f.Path)

		req := createIssueRequest{
			Fields: issueFields{
				Project:     projectKey{Key: c.project},
				Summary:     summary,
				Description: strings.Join(descParts, "\n"),
				IssueType:   issueType{Name: "Bug"},
			},
		}

		if highestSev == types.SeverityError {
			req.Fields.Priority = &priority{Name: "High"}
		} else if highestSev == types.SeverityWarning {
			req.Fields.Priority = &priority{Name: "Medium"}
		}

		key, err := c.createIssue(req)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: failed to create Jira issue for %s: %v\n", f.Path, err)
			continue
		}
		keys = append(keys, key)
	}

	return keys, nil
}

func (c *Client) createIssue(req createIssueRequest) (string, error) {
	url := fmt.Sprintf("%s/rest/api/2/issue", strings.TrimRight(c.host, "/"))

	data, err := json.Marshal(req)
	if err != nil {
		return "", fmt.Errorf("marshaling request: %w", err)
	}

	httpReq, err := http.NewRequest("POST", url, bytes.NewReader(data))
	if err != nil {
		return "", fmt.Errorf("creating request: %w", err)
	}

	httpReq.SetBasicAuth(c.email, c.token)
	httpReq.Header.Set("Content-Type", "application/json")
	httpReq.Header.Set("Accept", "application/json")

	resp, err := c.client.Do(httpReq)
	if err != nil {
		return "", fmt.Errorf("calling Jira API: %w", err)
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode >= 300 {
		return "", fmt.Errorf("Jira API error %d: %s", resp.StatusCode, string(body))
	}

	var result struct {
		Key string `json:"key"`
	}
	if err := json.Unmarshal(body, &result); err != nil {
		return "", fmt.Errorf("parsing response: %w", err)
	}

	return result.Key, nil
}
